export enum ErrorName {
  UNKNOWN_LLM_SOURCE_ERROR = 'UNKNOWN_LLM_SOURCE_ERROR',
  CONNECTION_REFUSED = 'CONNECTION_REFUSED',
  IRREGULAR_LOADED_MODEL_QUANTITY = 'IRREGULAR_LOADED_MODEL_QUANTITY',
  WAIFU_NOT_SELECTED = 'WAIFU_NOT_SELECTED',
}
